### ISSUE TITLE
Flash of wrong scroll position 

### ISSUE THREAD

**Issue by hsin421** [rackt/scroll-behavior#13]
I am using scroll to top behavior. It works great and I'm no longer in weird scroll positions in a new route. However, there's a flash or wrong position before flashing back to the top. 

I am using it with Redux-router:

reduxReactRouter({ routes, createHistory: useScrollToTopBehavior(createHistory) });

Thanks

**Comment by taion** [comment]
Yeah, I have a better idea for how to handle scrolling. Won't work for async routes but actually even now I don't support async routes so it's no real loss.

**Comment by taion** [comment]
Should be closed by #16.

**Comment by jackyon** [comment]
still have this issue. how to solve it? plz advise! thx!

**Comment by halt-hammerzeit** [comment]
@hsin421 Using this library with `redux-router` through `createHistory` won't work and you'll have jumping (buggy) scroll.
I managed to get it working though:
acdlite/redux-router#261
