### ISSUE TITLE
react router 2.0 support

### ISSUE THREAD

**Issue by tadeuszwojcik** [rackt/scroll-behavior#28]
Are there any plans to support react router 2.0?

**Comment by taion** [comment]
We're accepting PRs. Though this API just needs to be replaced.

**Comment by mmahalwy** [comment]
@taion any suggestions for a temporary fix? Like on leave global hook?

**Comment by cshenoy** [comment]
`browserHistory` in react-router is an object now so I just removed the last returning function at https://github.com/rackt/scroll-behavior/blob/master/modules/utils/createUseScroll.js#L3. Line 4 just becomes `const history = createHistory`. Been working fine for me.

**Comment by taion** [comment]
@mmahalwy For now, we can just bump up the dependency range. The history enhancer still works with the v2 history.

**Comment by mmahalwy** [comment]
@cshenoy ill give it a try

**Comment by apazzolini** [comment]
Per @cshenoy's suggestion, an alternative interim solution while waiting on this issue to be resolved is to do this so that you don't have to modify scroll-behavior code:

```js
import useScroll from 'scroll-behavior/lib/useStandardScroll';
import {browserHistory} from 'react-router';
const scrollHistory = useScroll(() => browserHistory)(); 
```

**Comment by taion** [comment]
I added 2.x compatibility. No changes needed, just the peer dependency bump.

**Comment by 0x80** [comment]
Where is this documented? I am failing to understand how to use this library with react-router 2.0 browserHistory, and I can't seem to find any examples.

**Comment by taion** [comment]
It's the standard "custom history" use codepath.

**Comment by 0x80** [comment]
Sorry for being thick but I don't follow. This is how I create the history to pass to Router but it doesn't seem to have the behavior:

```javascript
import { Router, useRouterHistory } from 'react-router'
import useScroll from 'scroll-behavior/lib/useStandardScroll'
import createBrowserHistory from 'history/lib/createBrowserHistory'

const createScrollHistory = useScroll(createBrowserHistory)
const appHistory = useRouterHistory(createScrollHistory)()
```

What did you mean by "use codepath"?

**Comment by gustavoguichard** [comment]
@0x80 follow @apazzolini 's comment ^^^
works like a charm!

**Comment by 0x80** [comment]
@gustavoguichard Weird that also doesn't work for me. I get no errors but using the back button doesn't restore the scroll position for me. I'm exporting the history from a module to use as a singleton everywhere I do a push() call.

**Comment by 0x80** [comment]
After some debugging I found that my issue was not with this module. The project I was working on had an `overflow-x: hidden` set on the body element to fix some IE issue. This weirdly blocks any scroll events from window, in Chrome at least. So the scroll was never recorded by scroll-behavior and POP restore was always 0. All is good now.

**Comment by StevenIseki** [comment]
I got this working with react-redux-router and react-router 2.0 plus server rendering with the help of @0x80 comment, and updating to version 0.3.2 of scroll-behavior as mentioned by @taion 

I have an [example](https://github.com/StevenIseki/react-router-redux-example) of it. What I did was as follows:

```jsx
import React from 'react'
import { render } from 'react-dom'
import { Provider } from 'react-redux'
import { Router, browserHistory, useRouterHistory } from 'react-router'
import { syncHistoryWithStore } from 'react-router-redux'
import useScroll from 'scroll-behavior/lib/useStandardScroll'
import createBrowserHistory from 'history/lib/createBrowserHistory'

import { configureStore } from './src/store'
import routes from './src/routes'

let state = window.__initialState__ || undefined
const store = configureStore(browserHistory, state)
const createScrollHistory = useScroll(createBrowserHistory)
const appHistory = useRouterHistory(createScrollHistory)()
const history = syncHistoryWithStore(appHistory, store)

render(
  <Provider store={store}>
    <Router history={history} routes={routes} />
  </Provider>,
  document.getElementById('mount')
)
```

**Comment by taion** [comment]
That looks about right to me.

**Comment by damassi** [comment]
The solution that worked for me was: 
```javascript

// configureHistory.js
import { browserHistory } from 'react-router'
import { syncHistoryWithStore } from 'react-router-redux'
import useScroll from 'scroll-behavior/lib/useStandardScroll'

export default function configureHistory(store) {
  const _browserHistory = useScroll(() => browserHistory)()
  return syncHistoryWithStore(_browserHistory, store)
}
```

**Comment by mmahalwy** [comment]
@StevenIseki I noticed you used `useRouterHistory`. How come? Trying to evaluate because other examples don't use it.

**Comment by dwilt** [comment]
@StevenIseki I'm using your setup that you've put out on your [repo](https://github.com/StevenIseki/react-router-redux-example) and loving it. Thanks.

I'm trying to update the config of `useScroll` so that it never updates the scroll position. Here's what I'm doing per the docs:

```javascript
const createScrollHistory = useScroll(createBrowserHistory, () => false);
````

However, it's not working at all. It's still scrolling to the top whenever I click a link. Any ideas?

**Comment by taion** [comment]
This API changed a few times since this was relevant. You should just be using react-router-scroll at this point, though.
