### ISSUE TITLE
Does scroll-behavior work with react-router querykey?

### ISSUE THREAD

**Issue by jcs12311** [rackt/scroll-behavior#32]
I dont't want to see ?_k=ckuvup pattern, so i disabled queryKey.
will it affect the useStandardScroll working?
actully, in my situation, disabled querykey or not didn't affect useStandardScroll, because it always can't record window scroll position, but it can go back to the scroll top.

**Comment by jcs12311** [comment]
When i click chrome's back button, the last page's querykey will be change, it's this situation normally?

**Comment by jcs12311** [comment]
i found that when i using chrome 48, useStandardScroll can't work.
and chrome 45, is work correctly.

**Comment by taion** [comment]
State management (i.e. queryKey) is required for scroll management.

**Comment by jcs12311** [comment]
sorry, my english is bad.
In chrome 48, i using queryKey, useStandardScroll still not working.....

**Comment by jcs12311** [comment]
"react-router": "^1.0.0",
"history": "^1.17.0",
"scroll-behavior": "^0.3.1",
sometimes useStandardScroll  is working, but record wrong scroll position.

**Comment by jcs12311** [comment]
maybe the last page's data is load from server, so useStandardScroll can't go back to the right position while the data not load yet??

**Comment by jcs12311** [comment]
@taion
