### ISSUE TITLE
Transfer repository out of Rackt

### ISSUE THREAD

**Issue by taion** [rackt/scroll-behavior#34]
Barring objections, I'm going to move this off Rackt, given insufficient maturity/usage.

cc @rackt/owners

**Comment by gaearon** [comment]
Agreed.
(I do feel guilty that we don’t offer a good solution though. It’s a regression from 0.x which offered good control over scroll behavior across routes.)

**Comment by taion** [comment]
This is roughly on par with what 0.13.x offered, and actually works a bit better for edge cases like hash history on Firefox. There's no per-route control, but I could add that. Otherwise it is a workable solution.

The bigger problems are:
- I'm not happy with the way the library currently looks from an API perspective; the current API rules out async route support, and is just clunky with React Router v2
- The issues with the library call for a (partial) rewrite rather than just maintenance, given the need for the API change
- I won't have time to do this in the near future, but I don't see anybody else I can shove this onto right now

**Comment by timdorr** [comment]
Where should it go to, though? I'd love something like a `rackt-incubator` org to put potential projects into and/or revitalize ones that need some love.

**Comment by timdorr** [comment]
Re: rackt/rackt.github.io#8

**Comment by taion** [comment]
I was going to do taion/scroll-behavior just because this really needs a rewrite rather than just maintenance.

**Comment by timdorr** [comment]
Cool. I'd do that and add a note at the top of the README about a call for maintainers.

**Comment by taion** [comment]
I mean, given that it's a rewrite... some of the code in this library might be useful, but really not that much. I'm going to go through with the move, though.
